### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by Onkelpuh** [AdyUPL/SupermarketSimulator-Addons#2]
File cannot be loaded because virus/Trojan is detected
please fix

**Comment by AdyUPL** [comment]
I don't know why 🤔
Only MaxSecure have problem with this..

https://www.virustotal.com/gui/file/c12239f131c0d8dc5202ed27f4bd349e46cd89c8ca9cf87691d173f076fd37f1/detection

**Comment by Onkelpuh** [comment]
I use Windows Defender
